### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/parser#1]
- [x] Remove the es6 classes from source code (preferring a pure functional approach)
- [x] Clean up the code
- [x] Write more tests
- [x] Add better parsing for `public` vs `private` tag javascript
- [x] Improve the codeclimate maintainability level
- [x] Get 100% coverage
